name: Fix PHP code style issues

on:
  push:
    branches: [main]
    paths:
      - "**.php"
  pull_request:
    branches: [main]
    paths:
      - "**.php"

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.2.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
